spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: fbrjs
    password: ss64267844!@
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create # create none update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug