name: CI/CD with Gradle and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup application.yml
        run: |
          cd ./src/main/resources
          
          # 디버깅 로그 추가
          echo "APPLICATION_DB: ${APPLICATION_DB}"
          echo "APPLICATION_AWS: ${APPLICATION_AWS}"
          echo "APPLICATION_JWT: ${APPLICATION_JWT}"
          echo "APPLICATION_SWAGGER: ${APPLICATION_SWAGGER}"

          # 각각의 시크릿을 개별 파일로 저장
          echo "${{ secrets.APPLICATION_DB }}" > application-db.yml
          echo "${{ secrets.APPLICATION_AWS }}" > application-aws.yml
          echo "${{ secrets.APPLICATION_JWT }}" > application-jwt.yml
          echo "${{ secrets.APPLICATION_SWAGGER }}" > application-swagger.yml

        shell: bash

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build -x test

      - name: docker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/clerker:latest .

      # 4. DockerHub 로그인
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker Hub 이미지 푸시
      - name: docker Hub push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/clerker:latest

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      - name: docker pull
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/clerker:latest

      - name: docker stop container
        run: sudo docker stop clerker:latest || true

      - name: docker run new container
        run: sudo docker run --name github-actions-demo --rm -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/clerker:latest

      - name: delete old docker image
        run: sudo docker image prune -f