name: CI/CD with Gradle and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup application.yml
        run: |
          cd ./src/main/resources
          
          touch ./application-db.yml
          touch ./application-aws.yml
          touch ./application-jwt.yml
          touch ./application-swagger.yml
          touch ./application-oauth.yml
          
          # 각각의 시크릿을 개별 파일로 저장
          echo "${{ secrets.APPLICATION_DB }}" >> ./application-db.yml
          echo "${{ secrets.APPLICATION_AWS }}" >> ./application-aws.yml
          echo "${{ secrets.APPLICATION_JWT }}" >> ./application-jwt.yml
          echo "${{ secrets.APPLICATION_SWAGGER }}" >> ./application-swagger.yml
          echo "${{ secrets.APPLICATION_OAUTH }}" >> ./application-oauth.yml

        shell: bash

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build -x test

      # Docker 관련 작업들은 push 시에만 실행되도록 설정
      - name: docker image build
        if: github.event_name == 'push'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/clerker:latest .

      # DockerHub 로그인
      - name: docker login
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Hub 이미지 푸시
      - name: docker Hub push
        if: github.event_name == 'push'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/clerker:latest

  run-docker-image-on-ec2:
    needs: build-docker-image
    #push 했을 때만 배포가 진행되도록
    if: github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - name: docker pull
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/clerker:latest

      - name: docker stop container'
        run: sudo docker stop clerker:latest || true

      - name: docker run new container
        run: sudo docker run --name github-actions-demo --rm -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/clerker:latest

      - name: delete old docker image
        run: sudo docker image prune -f
